version: "3.9"

services:
  web:
    container_name: book-manager
    build:
      context: .
      dockerfile: Dockerfile
    image: book-manager-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
