# Generated by Django 4.2.11 on 2024-11-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('History', 'History'), ('Poetry', 'Poetry'), ('Self-Help', 'Self-Help')], max_length=100, null=True),
        ),
    ]
