# Generated by Django 4.2.11 on 2024-12-03 20:26

from django.db import migrations, models
import django.db.models.deletion

def set_default_user(apps, schema_editor):
    Author = apps.get_model('book_manager', 'Author')
    User = apps.get_model('auth', 'User')
    # Try to get admin user, create if doesn't exist
    admin_user = User.objects.filter(username='admin').first()
    if not admin_user:
        admin_user = User.objects.create_superuser('admin', 'admin@example.com', 'admin')
    Author.objects.filter(created_by__isnull=True).update(created_by=admin_user)

class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0005_alter_readinglist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_by',
            field=models.ForeignKey(
                null=True,  # Allow null temporarily
                to='auth.User',
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        migrations.RunPython(set_default_user),
        migrations.AlterField(  # Make it non-nullable after setting defaults
            model_name='author',
            name='created_by',
            field=models.ForeignKey(
                null=False,
                to='auth.User',
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
    ]
